[project]
authors = ["Rajeeva-IITM <bt20d204@smail.iitm.ac.in>"]
channels = ["conda-forge", "bioconda"]
description = "Add a short description here"
name = "VCF2Seq"
platforms = ["linux-64"]
version = "0.1.0"

[system-requirements]
linux="3.10.0"
libc = { family="glibc", version="2.17" }

[tasks]

[dependencies]
hydra-core = ">=1.3.2,<2"
bcftools = ">=1.21,<2"
python-dotenv = ">=1.0.1,<2"
pre-commit = ">=4.0.1,<5"

[pypi-dependencies]
hydra-joblib-launcher = ">=1.2.0, <2"
